/**:
  ros__parameters:
    # Make MAVROS use the same GCS system_id that ArduSub expects
    system_id: 255       # typical GCS ID in ArduSub SITL
    component_id: 250    # arbitrary, can be something non-conflicting

    # Include both MAVROS (255) and autopilot (1) in the same link:
    fcu_url: "udp://:14550@192.168.2.1:14550/?ids=255,1"

    plugin_denylist:
      - ftp
      - px4flow
      - actuator_control
      - debug_value
      - global_position
      - distance_sensor
      - extras
      - wheel_odometry
      - image_pub
      - vibration
      - gps*
      - setpoint*
      - gimbal_control
      - local_position
      - geofence
      - fake_gps
      - camera
      - mission
      - trajectory
      - wind_estimation

/**/imu:
  ros__parameters:
    frame_id: "robot_real_base_link"
    # need find actual values
    # linear_acceleration_stdev: 0.0003
    # angular_velocity_stdev: 0.0003490659  # 0.02 degrees
    # orientation_stdev: 1.0
    # magnetic_stdev: 0.0
    # plugin_allowlist:
    #   - sys_status
